#
# Module manifest for module 'ComplexNumbers'
#
# Generated by: R D
#
# Generated on: 3/2/2017
#

@{

# Script module or binary module file associated with this manifest
# RootModule = 'ComplexNumbers.psm1'
ModuleToProcess = 'ComplexNumbers.psm1'

# Version number of this module.
ModuleVersion = '1.0.6'

# ID used to uniquely identify this module
GUID = '3d9df4bd-ac9d-4f2d-ae91-8072f0400e08'

# Author of this module
Author = 'R D'

# Company or vendor of this module
CompanyName = 'endowdly'

# Copyright statement for this module
Copyright = 'All Rights Reserved.'

# Description of the functionality provided by this module
Description = 'Complex Number support for PowerShell. Built for Stars ★'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = 'loadNumerics.ps1'

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = 'ComplexNumbers.Format.ps1xml'

# Modules to import as nested modules of the module specified in ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in ModuleToProcess
# PrivateData = ''

}

